### ISSUE TITLE
how to use Your code to generate the dicom from our own array

### ISSUE THREAD

**Issue by CXSunshine** [ryanneph/npy2dcm#1]

**Comment by ryanneph** [comment]
A basic example is as follows:
```python
# DEFINE GEOMETRY
if __name__ == "__main__":
    voxel = (1,1,1) # [unit: mm]
    size = np.ceil(np.array([101,101,300])/voxel).astype(int)
    frame = FrameOfReference(start=(0,0,0), spacing=voxel, size=size[::-1])
    arr = np.ones(size)
    vol = BaseVolume.fromArray(arr, frame)
    print('volume shape: '+str(arr.shape))
    vol.toDicom('water_phantom')
```

The size that I've chosen here is arbitrary and will change for your application. The `start` is the location in the CT scanner coordinate system where the first voxel in the array should be placed. You'll need to decide what this should be based on your applications. Both `spacing` and `start` arguments to the `FrameOfRefernce` constructor should be in (x,y,z) order and should have units of millimeter (mm). the `size` argument is also expected in (x,y,z) order and represents the number of voxels in each dimension of the volume.
